In [1]:
import pandas as pd
import geopandas as gpd
import glob

In [2]:
glacier_polys_fns = glob.glob("/data2/elilouis/hsfm-geomorph/data/mt_baker_mass_wasted/**/glaciers.geojson", recursive=True)

In [3]:
glaciers = pd.DataFrame()
for fn in glacier_polys_fns:
    glaciers = glaciers.append(gpd.read_file(fn))
glaciers = glaciers.to_crs("EPSG:32610")

/tmp/ipykernel_227215/1748184384.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  glaciers = glaciers.append(gpd.read_file(fn))
/tmp/ipykernel_227215/1748184384.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  glaciers = glaciers.append(gpd.read_file(fn))
/tmp/ipykernel_227215/1748184384.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  glaciers = glaciers.append(gpd.read_file(fn))
/tmp/ipykernel_227215/1748184384.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  glaciers = glaciers.append(gpd.read_file(fn))
/tmp/ipykernel_227215/1748184384.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  glaciers = glaciers.append(gpd.read_file(fn))
/tmp/ipykernel_227215/1748184384.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  glaciers = glaciers.append(gpd.read_file(fn))

In [4]:
relavent_glaciers = [
    'Deming Glacier WA', 
    'Rainbow Glacier WA',
    'Park Glacier WA',
    'Thunder Glacier WA', 
    'Squak Glacier WA', 
    'Boulder Glacier WA',
    'Talum Glaciers WA', 
    'Easton Glacier WA', 
    'Coleman Glacier WA',
    'Roosevelt Glacier WA', 
    'Mazama Glacier WA'
]
relavent_dates = ['1947_09_14', '1977_09_27', '1979_10_06', '2015_09_01']

In [5]:
glaciers = glaciers[glaciers.Name.isin(relavent_glaciers)]
glaciers = glaciers[glaciers.year.isin(relavent_dates)]

In [6]:
glaciers = pd.concat([
    glaciers.query("year == '1979_10_06' and Name != 'Rainbow Glacier WA' and Name != 'Park Glacier WA'"),
    glaciers.query("year == '1977_09_27' and Name == 'Rainbow Glacier WA'"),
    glaciers.query("year == '1977_09_27' and Name == 'Park Glacier WA'"),
    glaciers.query("year == '1947_09_14'"),
    glaciers.query("year == '2015_09_01'"),
])

In [7]:
glaciers['area'] = glaciers.geometry.area

In [8]:
glaciers = glaciers.groupby(['Name', 'year']).sum().reset_index()[['Name', 'year', 'area']]

In [9]:

glaciers['area difference'] = glaciers.groupby('Name')['area'].diff().reset_index(drop=True)
glaciers['area percent change'] = (glaciers['area difference'] / glaciers['area'].shift(1))*100

glaciers['area'] = glaciers['area']/1000000
glaciers['area difference'] = glaciers['area difference']/1000000

glaciers

,Name,year,area,area difference,area percent change
0,Boulder Glacier WA,1947_09_14,5.515658,NaN,NaN
1,Boulder Glacier WA,1979_10_06,6.441108,0.925450,16.778601
2,Boulder Glacier WA,2015_09_01,5.639315,-0.801794,-12.448072
3,Coleman Glacier WA,1947_09_14,6.455431,NaN,NaN
4,Coleman Glacier WA,1979_10_06,7.115175,0.659743,10.219971
5,Coleman Glacier WA,2015_09_01,6.700334,-0.414840,-5.830362
6,Deming Glacier WA,1947_09_14,4.927390,NaN,NaN
7,Deming Glacier WA,1979_10_06,5.126006,0.198616,4.030855
8,Deming Glacier WA,2015_09_01,4.757088,-0.368918,-7.196982
9,Easton Glacier WA,1947_09_14,2.644814,NaN,NaN
10,Easton Glacier WA,1979_10_06,2.897424,0.252610,9.551142
11,Easton Glacier WA,2015_09_01,2.712410,-0.185014,-6.385478
12,Mazama Glacier WA,1947_09_14,5.514445,NaN,NaN
13,Mazama Glacier WA,1979_10_06,5.582933,0.068488,1.241978
14,Mazama Glacier WA,2015_09_01,5.019562,-0.563371,-10.090955
15,Park Glacier WA,1947_09_14,2.743440,NaN,NaN
16,Park Glacier WA,1977_09_27,3.297547,0.554108,20.197547
17,Park Glacier WA,2015_09_01,2.907531,-0.390016,-11.827467
18,Rainbow Glacier WA,1947_09_14,2.327893,NaN,NaN
19,Rainbow Glacier WA,1977_09_27,2.698665,0.370772,15.927355
20,Rainbow Glacier WA,2015_09_01,2.012051,-0.686614,-25.442736
21,Roosevelt Glacier WA,1947_09_14,3.424140,NaN,NaN
22,Roosevelt Glacier WA,1979_10_06,3.800744,0.376604,10.998494
23,Roosevelt Glacier WA,2015_09_01,3.557903,-0.242841,-6.389293
24,Squak Glacier WA,1947_09_14,1.933566,NaN,NaN
25,Squak Glacier WA,1979_10_06,2.324257,0.390691,20.205716
26,Squak Glacier WA,2015_09_01,1.964959,-0.359298,-15.458619
27,Talum Glaciers WA,1947_09_14,1.890635,NaN,NaN
28,Talum Glaciers WA,1979_10_06,2.390145,0.499510,26.420219
29,Talum Glaciers WA,2015_09_01,1.908174,-0.481971,-20.164944
30,Thunder Glacier WA,1947_09_14,0.943570,NaN,NaN
31,Thunder Glacier WA,1979_10_06,0.970494,0.026924,2.853372
32,Thunder Glacier WA,2015_09_01,0.790051,-0.180443,-18.592922

In [10]:
glaciers = glaciers.pivot(index='Name', columns='year', values=['area', 'area difference', 'area percent change']).round(decimals=3)

In [11]:
glaciers

                           area                                   \
year                 1947_09_14 1977_09_27 1979_10_06 2015_09_01
Name
Boulder Glacier WA        5.516        NaN      6.441      5.639
Coleman Glacier WA        6.455        NaN      7.115      6.700
Deming Glacier WA         4.927        NaN      5.126      4.757
Easton Glacier WA         2.645        NaN      2.897      2.712
Mazama Glacier WA         5.514        NaN      5.583      5.020
Park Glacier WA           2.743      3.298        NaN      2.908
Rainbow Glacier WA        2.328      2.699        NaN      2.012
Roosevelt Glacier WA      3.424        NaN      3.801      3.558
Squak Glacier WA          1.934        NaN      2.324      1.965
Talum Glaciers WA         1.891        NaN      2.390      1.908
Thunder Glacier WA        0.944        NaN      0.970      0.790

                     area difference                                   \
year                      1947_09_14 1977_09_27 1979_10_06 2015_09_01
Name
Boulder Glacier WA               NaN        NaN      0.925     -0.802
Coleman Glacier WA               NaN        NaN      0.660     -0.415
Deming Glacier WA                NaN        NaN      0.199     -0.369
Easton Glacier WA                NaN        NaN      0.253     -0.185
Mazama Glacier WA                NaN        NaN      0.068     -0.563
Park Glacier WA                  NaN      0.554        NaN     -0.390
Rainbow Glacier WA               NaN      0.371        NaN     -0.687
Roosevelt Glacier WA             NaN        NaN      0.377     -0.243
Squak Glacier WA                 NaN        NaN      0.391     -0.359
Talum Glaciers WA                NaN        NaN      0.500     -0.482
Thunder Glacier WA               NaN        NaN      0.027     -0.180

                     area percent change
year                          1947_09_14 1977_09_27 1979_10_06 2015_09_01
Name
Boulder Glacier WA                   NaN        NaN     16.779    -12.448
Coleman Glacier WA                   NaN        NaN     10.220     -5.830
Deming Glacier WA                    NaN        NaN      4.031     -7.197
Easton Glacier WA                    NaN        NaN      9.551     -6.385
Mazama Glacier WA                    NaN        NaN      1.242    -10.091
Park Glacier WA                      NaN     20.198        NaN    -11.827
Rainbow Glacier WA                   NaN     15.927        NaN    -25.443
Roosevelt Glacier WA                 NaN        NaN     10.998     -6.389
Squak Glacier WA                     NaN        NaN     20.206    -15.459
Talum Glaciers WA                    NaN        NaN     26.420    -20.165
Thunder Glacier WA                   NaN        NaN      2.853    -18.593

In [12]:
glaciers.to_csv("outputs/final_figures_data/glacier_area.csv")
glaciers.to_pickle("outputs/glacier_area.pickle")